version: 2.0

jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: |
          sudo apt-get install cmake cppcheck python3-pip
          sudo pip3 install cpplint conan
          gem install pdd
          # conan remote add dronmdf https://api.bintray.com/conan/mdf/2out
          conan install . -s compiler.libcxx='libstdc++11' --build
          cmake .
          make VERBOSE=1
          #make test
      - store_test_results:
          path: .
